/**
 * Rule sections from SRD 5e
 */

export enum RuleSection {
  AbilityChecks = "ability-checks",
  AbilityScoresAndModifiers = "ability-scores-and-modifiers",
  ActionsInCombat = "actions-in-combat",
  AdvantageAndDisadvantage = "advantage-and-disadvantage",
  BetweenAdventures = "between-adventures",
  CastingASpell = "casting-a-spell",
  Cover = "cover",
  DamageAndHealing = "damage-and-healing",
  Diseases = "diseases",
  FantasyHistoricalPantheons = "fantasy-historical-pantheons",
  Madness = "madness",
  MakingAnAttack = "making-an-attack",
  MountedCombat = "mounted-combat",
  Movement = "movement",
  MovementAndPosition = "movement-and-position",
  Objects = "objects",
  Poisons = "poisons",
  ProficiencyBonus = "proficiency-bonus",
  Resting = "resting",
  SavingThrows = "saving-throws",
  SentientMagicItems = "sentient-magic-items",
  StandardExchangeRates = "standard-exchange-rates",
  TheEnvironment = "the-environment",
  TheOrderOfCombat = "the-order-of-combat",
  ThePlanesOfExistence = "the-planes-of-existence",
  Time = "time",
  Traps = "traps",
  UnderwaterCombat = "underwater-combat",
  UsingEachAbility = "using-each-ability",
  WhatIsASpell = "what-is-a-spell",
}
