export enum Condition {
  Blinded = "blinded",
  Charmed = "charmed",
  Deafened = "deafened",
  Frightened = "frightened",
  Grappled = "grappled",
  Exhaustion = "exhaustion",
  Incapacitated = "incapacitated",
  Invisible = "invisible",
  Paralyzed = "paralyzed",
  Petrified = "petrified",
  Poisoned = "poisoned",
  Prone = "prone",
  Restrained = "restrained",
  Stunned = "stunned",
  Unconscious = "unconscious",
}
